name: 'Your name here'
description: 'Provide a description here'
author: 'filinico'
branding:
  icon: git-branch
  color: green
inputs:
  GITHUB_TOKEN:
    description: "User token of service account."
    required: true
  JIRA_SUBDOMAIN:
    description: "subdomain to jira cloud"
    required: true
  JIRA_USER:
    description: "username for jira cloud"
    required: true
  JIRA_TOKEN:
    description: "token for jira cloud"
    required: true
  JIRA_PROJECT_ID:
    description: "project id from jira cloud"
    required: true
  JIRA_PROJECT_KEY:
    description: "project key from jira cloud"
    required: true
  JIRA_MASTER_PROJECT_ID:
    description: "master project id from jira cloud"
    required: true
  JIRA_MASTER_PROJECT_KEY:
    description: "master project key jira cloud"
    required: true
  JIRA_MASTER_ISSUE_TYPE:
    description: "master issue type id from jira cloud"
    required: true
  TAG_PREFIX:
    description: "prefix for the versioning"
    required: true
outputs:
  LAST_TAG_NAME:
    description: "name of the last tag found"
  FIX_VERSION:
    description: "current fix version"
  PRE_RELEASE:
    description: "Is the current release a prerelease? If yes, it will not link issues to master ticket"
  EXTRACTED_ISSUE_KEYS:
    description: "issue keys from git log"
  ISSUE_KEYS:
    description: "issue keys without current fix version"
  MASTER_TICKET_ISSUE_KEY:
    description: "master ticket for current fix version"
  LINKED_ISSUE_KEYS:
    description: "issues linked to master ticket for current fix version"
runs:
  using: 'node12'
  main: 'dist/index.js'
