name: 'Your name here'
description: 'Provide a description here'
author: 'filinico'
branding:
  icon: git-branch
  color: green
inputs:
  GITHUB_TOKEN:
    description: "User token of service account."
    required: true
  JIRA_SUBDOMAIN:
    description: "subdomain to jira cloud"
    required: true
  JIRA_USER:
    description: "username for jira cloud"
    required: true
  JIRA_TOKEN:
    description: "token for jira cloud"
    required: true
  JIRA_PROJECTS_IDS:
    description: "projects ids from jira cloud. list comma separated"
    required: true
  JIRA_PROJECTS_KEYS:
    description: "projects keys from jira cloud. list comma separated"
    required: true
  JIRA_MASTER_PROJECT_ID:
    description: "master project id from jira cloud"
    required: true
  JIRA_MASTER_PROJECT_KEY:
    description: "master project key jira cloud"
    required: true
  JIRA_MASTER_ISSUE_TYPE:
    description: "master issue type id from jira cloud"
    required: true
  TAG_PREFIX:
    description: "prefix for the versioning"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
