#!/usr/bin/bash

# use -t to configure token
while getopts ":t:r:v:p:" arg; do
  case $arg in
    t) tagPrefix=$OPTARG;;
    r) releaseVersion=$OPTARG;;
    v) previousVersion=$OPTARG;;
    p) projectsCommaSeparated=$OPTARG;;
    *) echo "Please provide the release version, tagPrefix and projects. usage: $0 [-t -r -v -p]" >&2
       exit 1 ;;
  esac
done

# Set comma as delimiter
IFS=','
#Read the split projects into an array based on comma delimiter
read -r -a projects <<< "$projectsCommaSeparated"

grepsArguments=""
for project in "${projects[@]}"
do
  grepsArguments="$grepsArguments --grep=\"^$project-[0-9].*\""
done

separator="|"
regex="$( printf "${separator}%s" "${projects[@]}" )"
regex="${regex:${#separator}}"
git fetch --prune --unshallow --tags
previousTag=$(git tag --list --sort=-version:refname "$tagPrefix$previousVersion*" | grep -oP --regexp="^$tagPrefix$previousVersion.[0-9]{1,6}$" | head -n 1)
if [ -z "$previousTag" ]
then
  tagVersion=$(echo -e "$previousVersion" | sed 's/\.//g')
  previousTag=$(git tag --list --sort=-version:refname "5.$tagVersion*" | head -n 1)
fi
revision=$(git log -g "origin/release/$releaseVersion" -1 --format=%H)
issueKeys=$(git log "$previousTag".."$revision" -i --pretty="format:%s""$grepsArguments" | grep -oP --regexp="($regex)-[0-9]{5,6}" | sort -u | tr '\n' ',' | sed 's/,$//g')
echo -e "$issueKeys"
